# Generated by Django 6.0.6 on 2026-07-15 19:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_openlibrary_key_externalbooksource'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='BookListing',
        ),
    ]
