# Generated by Django 6.0.6 on 2026-07-16 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_listing_booklisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklisting',
            name='images',
        ),
        migrations.CreateModel(
            name='BookListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('label', models.CharField(choices=[('FRONT_COVER', 'Front Cover'), ('BACK_COVER', 'Back Cover'), ('SPINE', 'Spine'), ('MIDDLE_PAGE', 'Middle Page'), ('DAMAGE_1', 'Damage 1'), ('DAMAGE_2', 'Damage 2')], default='FRONT_COVER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='marketplace.booklisting')),
            ],
        ),
    ]
