# Generated by Django 6.0.6 on 2026-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_booklisting_images_booklistingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='is_boosted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='booklisting',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
