# Generated by Django 6.0.6 on 2026-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personalization_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
