# Generated by Django 6.0.6 on 2026-08-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_subtitle'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequirement',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_requirements', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookrequirement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookrequirement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
