# Generated by Django 6.0.6 on 2026-07-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_cover_image_url_book_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='openlibrary_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ExternalBookSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('openlibrary', 'Open Library'), ('google_books', 'Google Books')], max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_source', to='books.book')),
            ],
        ),
    ]
