# Generated by Django 6.0.6 on 2026-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_openlibrary_key_externalbooksource'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text="Category subtitle/tagline e.g. 'Prepare to Succeed'", max_length=255),
        ),
    ]
