# Generated by Django 6.0.6 on 2026-06-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='city',
            new_name='district',
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
