# Generated by Django 6.0.6 on 2026-06-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_city_college_district_college_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='college',
            unique_together={('name', 'district', 'state')},
        ),
    ]
